blank_issues_enabled: false
contact_links:
  - name: Question?
    url: https://stackoverflow.com/questions/tagged/slack-keeper
    about: Please ask usage questions on Stack Overflow with the `slack-keeper` tag.