blank_issues_enabled: false
contact_links:
  - name: Question?
    url: https://github.com/slackhq/keeper/discussions/new?category=q-a
    about: Please ask usage questions in the repo's Discussions section.
